version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nft_test_api:latest
    ports:
      - "8080:8080"
    environment:
      DB_DRV: postgres
      DB_HOST: db
      DB_USER: nft_test_api
      DB_PASS: nft_test_api
      DB_NAME: nft_test_api
      DB_SSL_MODE: disable
    working_dir: /app
    links:
      - db

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=nft_test_api
      - POSTGRES_PASSWORD=nft_test_api
      - POSTGRES_DB=nft_test_api
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
